name: Daily test run

on:
  schedule:
    - cron: '11 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Swap to php 7.4
      run: rm /usr/bin/php && ln -s /usr/bin/php7.4 /usr/bin/php

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Test
      run: composer test
